from service_common.constants import *


USER_IS_NOT_AUTHORIZED = HTTP_403_FORBIDDEN
OTP_VERIFICATION_LIMIT_REACHED = HTTP_429_TOO_MANY_REQUESTS
RECORD_NOT_FOUND = HTTP_404_NOT_FOUND
MISSING_DATA = HTTP_422_UNPROCESSABLE_ENTITY
USER_TOKEN_ERROR = 452
USER_TOKEN_EXPIRED = 453
USER_TOKEN_INVALID = 454
OTP_INVALID = 455
USER_NOT_REGISTERED = 456
RESPONSE_OK = HTTP_200_OK
AUTHORIZATION_REQUIRED = 457
USER_AUTHENTICATION_FAILED = 458


